# Generated by Django 4.2.7 on 2026-02-28 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcards",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="cardconnection",
            name="source_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_connections",
                to="stories.flashcard",
            ),
        ),
        migrations.AddField(
            model_name="cardconnection",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="cardconnection",
            name="target_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_connections",
                to="stories.flashcard",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cardconnection",
            unique_together={("source_card", "target_card")},
        ),
    ]
